// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: proto/spinoza.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpinozaServiceClient is the client API for SpinozaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpinozaServiceClient interface {
	// Compress and then upload the image to the CDN provider
	Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadReply, error)
}

type spinozaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpinozaServiceClient(cc grpc.ClientConnInterface) SpinozaServiceClient {
	return &spinozaServiceClient{cc}
}

func (c *spinozaServiceClient) Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadReply, error) {
	out := new(UploadReply)
	err := c.cc.Invoke(ctx, "/spinoza.SpinozaService/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpinozaServiceServer is the server API for SpinozaService service.
// All implementations must embed UnimplementedSpinozaServiceServer
// for forward compatibility
type SpinozaServiceServer interface {
	// Compress and then upload the image to the CDN provider
	Upload(context.Context, *UploadRequest) (*UploadReply, error)
	mustEmbedUnimplementedSpinozaServiceServer()
}

// UnimplementedSpinozaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSpinozaServiceServer struct {
}

func (UnimplementedSpinozaServiceServer) Upload(context.Context, *UploadRequest) (*UploadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedSpinozaServiceServer) mustEmbedUnimplementedSpinozaServiceServer() {}

// UnsafeSpinozaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpinozaServiceServer will
// result in compilation errors.
type UnsafeSpinozaServiceServer interface {
	mustEmbedUnimplementedSpinozaServiceServer()
}

func RegisterSpinozaServiceServer(s grpc.ServiceRegistrar, srv SpinozaServiceServer) {
	s.RegisterService(&SpinozaService_ServiceDesc, srv)
}

func _SpinozaService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpinozaServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spinoza.SpinozaService/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpinozaServiceServer).Upload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpinozaService_ServiceDesc is the grpc.ServiceDesc for SpinozaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpinozaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spinoza.SpinozaService",
	HandlerType: (*SpinozaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _SpinozaService_Upload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/spinoza.proto",
}
