name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  gravitalia:
    name: Publish Spinoza
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the hello-docker Docker image
      run: |
            docker build . --tag ghcr.io/gravitalia/spinoza:latest
            docker run ghcr.io/gravitalia/spinoza:latest
            docker push ghcr.io/gravitalia/spinoza:latest
